
const one = document.getElementById("pressone")
const two = document.getElementById("presstwo")
const three = document.getElementById("pressthree")
const four = document.getElementById("pressfour")
const five = document.getElementById("pressfive")
const slide= document.querySelector(".slide")
one.addEventListener("click", () => {
    slide.classList.add("withone")
    slide.classList.remove("withtwo")
    slide.classList.remove("withthree")
    slide.classList.remove("withfour")
    slide.classList.remove("withfive")
} )
two.addEventListener("click", () => {
    slide.classList.remove("withone")
    slide.classList.add("withtwo")
    slide.classList.remove("withthree")
    slide.classList.remove("withfour")
    slide.classList.remove("withfive")
} )
three.addEventListener("click", () => {
    slide.classList.remove("withone")
    slide.classList.remove("withtwo")
    slide.classList.add("withthree")
    slide.classList.remove("withfour")
    slide.classList.remove("withfive")
} )
four.addEventListener("click", () => {
    slide.classList.remove("withone")
    slide.classList.remove("withtwo")
    slide.classList.remove("withthree")
    slide.classList.add("withfour")
    slide.classList.remove("withfive")
} )
five.addEventListener("click", () => {
    slide.classList.remove("withone")
    slide.classList.remove("withtwo")
    slide.classList.remove("withthree")
    slide.classList.remove("withfour")
    slide.classList.add("withfive")
} )